# Generated by Django 5.0 on 2025-11-17 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="nom de l'entreprise"
                    ),
                ),
                (
                    "cfe_number",
                    models.CharField(
                        help_text="Centre de Formalités des Entreprises",
                        max_length=50,
                        unique=True,
                        verbose_name="numéro CFE",
                    ),
                ),
                ("address", models.TextField(verbose_name="adresse")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="email de l'entreprise",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description de l'entreprise",
                        verbose_name="description",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="site web"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si l'entreprise est active",
                        verbose_name="active",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "entreprise",
                "verbose_name_plural": "entreprises",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="companies_c_user_id_00a4ee_idx",
                    ),
                    models.Index(
                        fields=["cfe_number"], name="companies_c_cfe_num_aa58e4_idx"
                    ),
                ],
                "unique_together": {("user", "name")},
            },
        ),
    ]
