# Generated by Django 5.0 on 2025-11-17 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="titre")),
                ("content", models.TextField(verbose_name="contenu")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("PUBLISHED", "Publié"),
                            ("ARCHIVED", "Archivé"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="publications/%Y/%m/%d/",
                        verbose_name="image",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="nombre de vues"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de publication"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Tags séparés par des virgules",
                        max_length=255,
                        verbose_name="tags",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="auteur",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Entreprise associée à la publication (optionnel)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="companies.company",
                        verbose_name="entreprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "publication",
                "verbose_name_plural": "publications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["author", "status"],
                        name="publication_author__bf6013_idx",
                    ),
                    models.Index(
                        fields=["company"], name="publication_company_06464b_idx"
                    ),
                    models.Index(
                        fields=["status", "-published_at"],
                        name="publication_status_2897c2_idx",
                    ),
                    models.Index(fields=["slug"], name="publication_slug_c19642_idx"),
                ],
            },
        ),
    ]
